/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package com.dperez.passwordhasher;

import com.dperez.passwordhasher.controladores.ControladorSeguridad;


/**
 *
 * @author dperez
 */
public class PasswordHasher extends javax.swing.JInternalFrame {
    private static ControladorSeguridad cSeg;
    /**
     * Creates new form PasswordHasher
     */
    public PasswordHasher() {
        initComponents();
        cSeg = new ControladorSeguridad();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoMensajes = new javax.swing.JDialog();
        mensajeLabel = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        passwordTextfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hashedPasswordTextfield = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        saltTextfield = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        hashedPasswordLabel = new javax.swing.JLabel();
        saltLabel = new javax.swing.JLabel();
        generarButton = new javax.swing.JButton();

        dialogoMensajes.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogoMensajes.setTitle("Error");
        dialogoMensajes.setAlwaysOnTop(true);
        dialogoMensajes.setMinimumSize(new java.awt.Dimension(200, 100));
        dialogoMensajes.setResizable(false);
        dialogoMensajes.setType(java.awt.Window.Type.POPUP);

        mensajeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeLabel.setText("No se ingreso password!");

        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoMensajesLayout = new javax.swing.GroupLayout(dialogoMensajes.getContentPane());
        dialogoMensajes.getContentPane().setLayout(dialogoMensajesLayout);
        dialogoMensajesLayout.setHorizontalGroup(
            dialogoMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoMensajesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(dialogoMensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogoMensajesLayout.setVerticalGroup(
            dialogoMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoMensajesLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(mensajeLabel)
                .addGap(18, 18, 18)
                .addComponent(botonCerrar)
                .addGap(18, 18, 18))
        );

        mensajeLabel.getAccessibleContext().setAccessibleName("mensajeLabel");

        setMinimumSize(new java.awt.Dimension(390, 290));
        setPreferredSize(new java.awt.Dimension(390, 290));
        getContentPane().setLayout(null);
        getContentPane().add(passwordTextfield);
        passwordTextfield.setBounds(157, 40, 210, 22);

        hashedPasswordTextfield.setEditable(false);
        hashedPasswordTextfield.setColumns(20);
        hashedPasswordTextfield.setLineWrap(true);
        hashedPasswordTextfield.setRows(3);
        jScrollPane1.setViewportView(hashedPasswordTextfield);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(157, 70, 210, 71);

        saltTextfield.setEditable(false);
        saltTextfield.setColumns(20);
        saltTextfield.setLineWrap(true);
        saltTextfield.setRows(3);
        jScrollPane2.setViewportView(saltTextfield);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(157, 150, 210, 68);

        jLabel1.setText("Password Hasher (SHA-256)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 360, 16);

        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(10, 44, 130, 16);

        hashedPasswordLabel.setText("Hashed Password");
        getContentPane().add(hashedPasswordLabel);
        hashedPasswordLabel.setBounds(10, 64, 140, 16);

        saltLabel.setText("Salt (Password Key)");
        getContentPane().add(saltLabel);
        saltLabel.setBounds(10, 150, 130, 16);

        generarButton.setText("Generar");
        generarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(generarButton);
        generarButton.setBounds(240, 220, 124, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarButtonActionPerformed
        String passToHash = this.passwordTextfield.getText();
        if(passToHash.isEmpty()){
            dialogoMensajes.setModal(true);
            dialogoMensajes.setVisible(true);
            dialogoMensajes.setResizable(false);
        }else{
            String[] res;
            res = cSeg.getPasswordSeguro(passToHash);
            String hashedPass = res[1];
            String passSalt = res[0];
            this.hashedPasswordTextfield.setText(hashedPass);
            this.saltTextfield.setText(passSalt);
        }
    }//GEN-LAST:event_generarButtonActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        dialogoMensajes.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JDialog dialogoMensajes;
    private javax.swing.JButton generarButton;
    private javax.swing.JLabel hashedPasswordLabel;
    private javax.swing.JTextArea hashedPasswordTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextfield;
    private javax.swing.JLabel saltLabel;
    private javax.swing.JTextArea saltTextfield;
    // End of variables declaration//GEN-END:variables
}
